
const gameData = {
  words: {
    vi: [
      "Chó", "Mèo", "Voi", "Gà", "Lợn", "Bò", "Cá", "Chim", "Rắn", "Chuột",
      "Táo", "Chuối", "Cam", "Xoài", "Dừa", "Ổi", "Mít", "Măng cụt", "Sầu riêng", "Nho",
      "Việt Nam", "Pháp", "Đức", "Mỹ", "Nhật", "Trung Quốc", "Anh", "Ý", "Nga", "Hàn Quốc",
      "Hà Nội", "Paris", "Berlin", "London", "Tokyo", "Bắc Kinh", "Moscow", "Seoul", "Rome", "Madrid",
      "Guitar", "Piano", "Trống", "Sáo", "Violin", "Hạc cầm", "Kèn", "Flute", "Cello", "Bass",
      "Bóng đá", "Tennis", "Bơi lội", "Chạy", "Cầu lông", "Bóng rổ", "Voley", "Golf", "Boxing", "Yoga",
      "Đỏ", "Xanh", "Vàng", "Trắng", "Đen", "Tím", "Hồng", "Cam", "Nâu", "Xám",
      "Mặt trời", "Mặt trăng", "Sao", "Trái đất", "Sao Hỏa", "Sao Kim", "Sao Thủy", "Sao Mộc", "Sao Thổ", "Thiên Hà",
      "Nước", "Lửa", "Đất", "Không khí", "Kim loại", "Gỗ", "Đá", "Cát", "Băng", "Hơi",
      "Bác sĩ", "Giáo viên", "Kỹ sư", "Luật sư", "Nông dân", "Thợ xây", "Đầu bếp", "Y tá", "Phi công", "Lái xe",
      "Xe hơi", "Máy bay", "Tàu", "Xe đạp", "Xe máy", "Tàu điện", "Tên lửa", "Trực thăng", "Thuyền", "Xe buýt",
      "Nhà", "Trường", "Bệnh viện", "Siêu thị", "Công viên", "Bảo tàng", "Rạp phim", "Nhà hàng", "Khách sạn", "Sân bay",
      "Sách", "Bút", "Giấy", "Máy tính", "Điện thoại", "Ti vi", "Radio", "Đồng hồ", "Máy ảnh", "Kính",
      "Mưa", "Tuyết", "Gió", "Sương", "Mây", "Nắng", "Sấm", "Chớp", "Lũ", "Hạn",
      "Yêu", "Ghét", "Vui", "Buồn", "Giận", "Sợ", "Ngạc nhiên", "Bình tĩnh", "Lo lắng", "Hạnh phúc",
      "Một", "Hai", "Ba", "Bốn", "Năm", "Sáu", "Bảy", "Tám", "Chín", "Mười",
      "Sáng", "Trưa", "Chiều", "Tối", "Đêm", "Bình minh", "Hoàng hôn", "Nửa đêm", "Buổi sáng", "Buổi chiều",
      "Mùa xuân", "Mùa hạ", "Mùa thu", "Mùa đông", "Tết", "Giáng sinh", "Lễ", "Sinh nhật", "Cưới", "Tốt nghiệp",
      "Ăn", "Uống", "Ngủ", "Chạy", "Nhảy", "Hát", "Nói", "Nghe", "Nhìn", "Suy nghĩ",
      "Lớn", "Nhỏ", "Cao", "Thấp", "Dài", "Ngắn", "Nặng", "Nhẹ", "Nhanh", "Chậm"
    ],
    en: [
      "Dog", "Cat", "Elephant", "Chicken", "Pig", "Cow", "Fish", "Bird", "Snake", "Mouse",
      "Apple", "Banana", "Orange", "Mango", "Coconut", "Guava", "Jackfruit", "Mangosteen", "Durian", "Grape",
      "Vietnam", "France", "Germany", "America", "Japan", "China", "England", "Italy", "Russia", "Korea",
      "Hanoi", "Paris", "Berlin", "London", "Tokyo", "Beijing", "Moscow", "Seoul", "Rome", "Madrid",
      "Guitar", "Piano", "Drums", "Flute", "Violin", "Harp", "Trumpet", "Saxophone", "Cello", "Bass",
      "Football", "Tennis", "Swimming", "Running", "Badminton", "Basketball", "Volleyball", "Golf", "Boxing", "Yoga",
      "Red", "Blue", "Yellow", "White", "Black", "Purple", "Pink", "Orange", "Brown", "Gray",
      "Sun", "Moon", "Star", "Earth", "Mars", "Venus", "Mercury", "Jupiter", "Saturn", "Galaxy",
      "Water", "Fire", "Earth", "Air", "Metal", "Wood", "Stone", "Sand", "Ice", "Steam",
      "Doctor", "Teacher", "Engineer", "Lawyer", "Farmer", "Builder", "Chef", "Nurse", "Pilot", "Driver",
      "Car", "Plane", "Ship", "Bicycle", "Motorcycle", "Train", "Rocket", "Helicopter", "Boat", "Bus",
      "House", "School", "Hospital", "Supermarket", "Park", "Museum", "Cinema", "Restaurant", "Hotel", "Airport",
      "Book", "Pen", "Paper", "Computer", "Phone", "Television", "Radio", "Clock", "Camera", "Glasses",
      "Rain", "Snow", "Wind", "Fog", "Cloud", "Sunshine", "Thunder", "Lightning", "Flood", "Drought",
      "Love", "Hate", "Happy", "Sad", "Angry", "Afraid", "Surprised", "Calm", "Worried", "Joy",
      "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
      "Morning", "Noon", "Afternoon", "Evening", "Night", "Dawn", "Dusk", "Midnight", "Sunrise", "Sunset",
      "Spring", "Summer", "Autumn", "Winter", "New Year", "Christmas", "Holiday", "Birthday", "Wedding", "Graduation",
      "Eat", "Drink", "Sleep", "Run", "Dance", "Sing", "Talk", "Listen", "See", "Think",
      "Big", "Small", "Tall", "Short", "Long", "Brief", "Heavy", "Light", "Fast", "Slow"
    ],
    fr: [
      "Chien", "Chat", "Éléphant", "Poulet", "Cochon", "Vache", "Poisson", "Oiseau", "Serpent", "Souris",
      "Pomme", "Banane", "Orange", "Mangue", "Noix de coco", "Goyave", "Jacquier", "Mangoustan", "Durian", "Raisin",
      "Vietnam", "France", "Allemagne", "Amérique", "Japon", "Chine", "Angleterre", "Italie", "Russie", "Corée",
      "Hanoï", "Paris", "Berlin", "Londres", "Tokyo", "Pékin", "Moscou", "Séoul", "Rome", "Madrid",
      "Guitare", "Piano", "Batterie", "Flûte", "Violon", "Harpe", "Trompette", "Saxophone", "Violoncelle", "Basse",
      "Football", "Tennis", "Natation", "Course", "Badminton", "Basketball", "Volleyball", "Golf", "Boxe", "Yoga",
      "Rouge", "Bleu", "Jaune", "Blanc", "Noir", "Violet", "Rose", "Orange", "Marron", "Gris",
      "Soleil", "Lune", "Étoile", "Terre", "Mars", "Vénus", "Mercure", "Jupiter", "Saturne", "Galaxie",
      "Eau", "Feu", "Terre", "Air", "Métal", "Bois", "Pierre", "Sable", "Glace", "Vapeur",
      "Médecin", "Professeur", "Ingénieur", "Avocat", "Agriculteur", "Constructeur", "Chef", "Infirmière", "Pilote", "Chauffeur",
      "Voiture", "Avion", "Bateau", "Vélo", "Moto", "Train", "Fusée", "Hélicoptère", "Canot", "Bus",
      "Maison", "École", "Hôpital", "Supermarché", "Parc", "Musée", "Cinéma", "Restaurant", "Hôtel", "Aéroport",
      "Livre", "Stylo", "Papier", "Ordinateur", "Téléphone", "Télévision", "Radio", "Horloge", "Appareil photo", "Lunettes",
      "Pluie", "Neige", "Vent", "Brouillard", "Nuage", "Soleil", "Tonnerre", "Éclair", "Inondation", "Sécheresse",
      "Amour", "Haine", "Heureux", "Triste", "Fâché", "Effrayé", "Surpris", "Calme", "Inquiet", "Joie",
      "Un", "Deux", "Trois", "Quatre", "Cinq", "Six", "Sept", "Huit", "Neuf", "Dix",
      "Matin", "Midi", "Après-midi", "Soir", "Nuit", "Aube", "Crépuscule", "Minuit", "Lever du soleil", "Coucher du soleil",
      "Printemps", "Été", "Automne", "Hiver", "Nouvel An", "Noël", "Vacances", "Anniversaire", "Mariage", "Remise des diplômes",
      "Manger", "Boire", "Dormir", "Courir", "Danser", "Chanter", "Parler", "Écouter", "Voir", "Penser",
      "Grand", "Petit", "Grand", "Court", "Long", "Bref", "Lourd", "Léger", "Rapide", "Lent"
    ],
    de: [
      "Hund", "Katze", "Elefant", "Huhn", "Schwein", "Kuh", "Fisch", "Vogel", "Schlange", "Maus",
      "Apfel", "Banane", "Orange", "Mango", "Kokosnuss", "Guave", "Jackfrucht", "Mangostane", "Durian", "Traube",
      "Vietnam", "Frankreich", "Deutschland", "Amerika", "Japan", "China", "England", "Italien", "Russland", "Korea",
      "Hanoi", "Paris", "Berlin", "London", "Tokio", "Peking", "Moskau", "Seoul", "Rom", "Madrid",
      "Gitarre", "Klavier", "Schlagzeug", "Flöte", "Violine", "Harfe", "Trompete", "Saxophon", "Cello", "Bass",
      "Fußball", "Tennis", "Schwimmen", "Laufen", "Badminton", "Basketball", "Volleyball", "Golf", "Boxen", "Yoga",
      "Rot", "Blau", "Gelb", "Weiß", "Schwarz", "Lila", "Rosa", "Orange", "Braun", "Grau",
      "Sonne", "Mond", "Stern", "Erde", "Mars", "Venus", "Merkur", "Jupiter", "Saturn", "Galaxie",
      "Wasser", "Feuer", "Erde", "Luft", "Metall", "Holz", "Stein", "Sand", "Eis", "Dampf",
      "Arzt", "Lehrer", "Ingenieur", "Anwalt", "Bauer", "Bauarbeiter", "Koch", "Krankenschwester", "Pilot", "Fahrer",
      "Auto", "Flugzeug", "Schiff", "Fahrrad", "Motorrad", "Zug", "Rakete", "Hubschrauber", "Boot", "Bus",
      "Haus", "Schule", "Krankenhaus", "Supermarkt", "Park", "Museum", "Kino", "Restaurant", "Hotel", "Flughafen",
      "Buch", "Stift", "Papier", "Computer", "Telefon", "Fernseher", "Radio", "Uhr", "Kamera", "Brille",
      "Regen", "Schnee", "Wind", "Nebel", "Wolke", "Sonnenschein", "Donner", "Blitz", "Überschwemmung", "Dürre",
      "Liebe", "Hass", "Glücklich", "Traurig", "Wütend", "Ängstlich", "Überrascht", "Ruhig", "Besorgt", "Freude",
      "Eins", "Zwei", "Drei", "Vier", "Fünf", "Sechs", "Sieben", "Acht", "Neun", "Zehn",
      "Morgen", "Mittag", "Nachmittag", "Abend", "Nacht", "Morgendämmerung", "Abenddämmerung", "Mitternacht", "Sonnenaufgang", "Sonnenuntergang",
      "Frühling", "Sommer", "Herbst", "Winter", "Neujahr", "Weihnachten", "Urlaub", "Geburtstag", "Hochzeit", "Abschluss",
      "Essen", "Trinken", "Schlafen", "Laufen", "Tanzen", "Singen", "Sprechen", "Hören", "Sehen", "Denken",
      "Groß", "Klein", "Groß", "Kurz", "Lang", "Kurz", "Schwer", "Leicht", "Schnell", "Langsam"
    ]
  },
  
  categories: {
    vi: {
      "Động vật": ["Chó", "Mèo", "Voi", "Gà", "Lợn", "Bò", "Cá", "Chim", "Rắn", "Chuột"],
      "Trái cây": ["Táo", "Chuối", "Cam", "Xoài", "Dừa", "Ổi", "Mít", "Măng cụt", "Sầu riêng", "Nho"],
      "Quốc gia": ["Việt Nam", "Pháp", "Đức", "Mỹ", "Nhật", "Trung Quốc", "Anh", "Ý", "Nga", "Hàn Quốc"],
      "Thủ đô": ["Hà Nội", "Paris", "Berlin", "London", "Tokyo", "Bắc Kinh", "Moscow", "Seoul", "Rome", "Madrid"],
      "Nhạc cụ": ["Guitar", "Piano", "Trống", "Sáo", "Violin", "Hạc cầm", "Kèn", "Flute", "Cello", "Bass"],
      "Thể thao": ["Bóng đá", "Tennis", "Bơi lội", "Chạy", "Cầu lông", "Bóng rổ", "Voley", "Golf", "Boxing", "Yoga"],
      "Màu sắc": ["Đỏ", "Xanh", "Vàng", "Trắng", "Đen", "Tím", "Hồng", "Cam", "Nâu", "Xám"],
      "Hành tinh": ["Mặt trời", "Mặt trăng", "Sao", "Trái đất", "Sao Hỏa", "Sao Kim", "Sao Thủy", "Sao Mộc", "Sao Thổ"],
      "Nghề nghiệp": ["Bác sĩ", "Giáo viên", "Kỹ sư", "Luật sư", "Nông dân", "Thợ xây", "Đầu bếp", "Y tá", "Phi công", "Lái xe"],
      "Phương tiện": ["Xe hơi", "Máy bay", "Tàu", "Xe đạp", "Xe máy", "Tàu điện", "Tên lửa", "Trực thăng", "Thuyền", "Xe buýt"],
      "Địa điểm": ["Nhà", "Trường", "Bệnh viện", "Siêu thị", "Công viên", "Bảo tàng", "Rạp phim", "Nhà hàng", "Khách sạn", "Sân bay"],
      "Đồ vật": ["Sách", "Bút", "Giấy", "Máy tính", "Điện thoại", "Ti vi", "Radio", "Đồng hồ", "Máy ảnh", "Kính"],
      "Thời tiết": ["Mưa", "Tuyết", "Gió", "Sương", "Mây", "Nắng", "Sấm", "Chớp", "Lũ", "Hạn"],
      "Cảm xúc": ["Yêu", "Ghét", "Vui", "Buồn", "Giận", "Sợ", "Ngạc nhiên", "Bình tĩnh", "Lo lắng", "Hạnh phúc"]
    },
    en: {
      "Animals": ["Dog", "Cat", "Elephant", "Chicken", "Pig", "Cow", "Fish", "Bird", "Snake", "Mouse"],
      "Fruits": ["Apple", "Banana", "Orange", "Mango", "Coconut", "Guava", "Jackfruit", "Mangosteen", "Durian", "Grape"],
      "Countries": ["Vietnam", "France", "Germany", "America", "Japan", "China", "England", "Italy", "Russia", "Korea"],
      "Capitals": ["Hanoi", "Paris", "Berlin", "London", "Tokyo", "Beijing", "Moscow", "Seoul", "Rome", "Madrid"],
      "Instruments": ["Guitar", "Piano", "Drums", "Flute", "Violin", "Harp", "Trumpet", "Saxophone", "Cello", "Bass"],
      "Sports": ["Football", "Tennis", "Swimming", "Running", "Badminton", "Basketball", "Volleyball", "Golf", "Boxing", "Yoga"],
      "Colors": ["Red", "Blue", "Yellow", "White", "Black", "Purple", "Pink", "Orange", "Brown", "Gray"],
      "Celestial": ["Sun", "Moon", "Star", "Earth", "Mars", "Venus", "Mercury", "Jupiter", "Saturn", "Galaxy"],
      "Professions": ["Doctor", "Teacher", "Engineer", "Lawyer", "Farmer", "Builder", "Chef", "Nurse", "Pilot", "Driver"],
      "Vehicles": ["Car", "Plane", "Ship", "Bicycle", "Motorcycle", "Train", "Rocket", "Helicopter", "Boat", "Bus"],
      "Places": ["House", "School", "Hospital", "Supermarket", "Park", "Museum", "Cinema", "Restaurant", "Hotel", "Airport"],
      "Objects": ["Book", "Pen", "Paper", "Computer", "Phone", "Television", "Radio", "Clock", "Camera", "Glasses"],
      "Weather": ["Rain", "Snow", "Wind", "Fog", "Cloud", "Sunshine", "Thunder", "Lightning", "Flood", "Drought"],
      "Emotions": ["Love", "Hate", "Happy", "Sad", "Angry", "Afraid", "Surprised", "Calm", "Worried", "Joy"]
    },
    fr: {
      "Animaux": ["Chien", "Chat", "Éléphant", "Poulet", "Cochon", "Vache", "Poisson", "Oiseau", "Serpent", "Souris"],
      "Fruits": ["Pomme", "Banane", "Orange", "Mangue", "Noix de coco", "Goyave", "Jacquier", "Mangoustan", "Durian", "Raisin"],
      "Pays": ["Vietnam", "France", "Allemagne", "Amérique", "Japon", "Chine", "Angleterre", "Italie", "Russie", "Corée"],
      "Capitales": ["Hanoï", "Paris", "Berlin", "Londres", "Tokyo", "Pékin", "Moscou", "Séoul", "Rome", "Madrid"],
      "Instruments": ["Guitare", "Piano", "Batterie", "Flûte", "Violon", "Harpe", "Trompette", "Saxophone", "Violoncelle", "Basse"],
      "Sports": ["Football", "Tennis", "Natation", "Course", "Badminton", "Basketball", "Volleyball", "Golf", "Boxe", "Yoga"],
      "Couleurs": ["Rouge", "Bleu", "Jaune", "Blanc", "Noir", "Violet", "Rose", "Orange", "Marron", "Gris"],
      "Céleste": ["Soleil", "Lune", "Étoile", "Terre", "Mars", "Vénus", "Mercure", "Jupiter", "Saturne", "Galaxie"],
      "Professions": ["Médecin", "Professeur", "Ingénieur", "Avocat", "Agriculteur", "Constructeur", "Chef", "Infirmière", "Pilote", "Chauffeur"],
      "Véhicules": ["Voiture", "Avion", "Bateau", "Vélo", "Moto", "Train", "Fusée", "Hélicoptère", "Canot", "Bus"],
      "Lieux": ["Maison", "École", "Hôpital", "Supermarché", "Parc", "Musée", "Cinéma", "Restaurant", "Hôtel", "Aéroport"],
      "Objets": ["Livre", "Stylo", "Papier", "Ordinateur", "Téléphone", "Télévision", "Radio", "Horloge", "Appareil photo", "Lunettes"],
      "Météo": ["Pluie", "Neige", "Vent", "Brouillard", "Nuage", "Soleil", "Tonnerre", "Éclair", "Inondation", "Sécheresse"],
      "Émotions": ["Amour", "Haine", "Heureux", "Triste", "Fâché", "Effrayé", "Surpris", "Calme", "Inquiet", "Joie"]
    },
    de: {
      "Tiere": ["Hund", "Katze", "Elefant", "Huhn", "Schwein", "Kuh", "Fisch", "Vogel", "Schlange", "Maus"],
      "Früchte": ["Apfel", "Banane", "Orange", "Mango", "Kokosnuss", "Guave", "Jackfrucht", "Mangostane", "Durian", "Traube"],
      "Länder": ["Vietnam", "Frankreich", "Deutschland", "Amerika", "Japan", "China", "England", "Italien", "Russland", "Korea"],
      "Hauptstädte": ["Hanoi", "Paris", "Berlin", "London", "Tokio", "Peking", "Moskau", "Seoul", "Rom", "Madrid"],
      "Instrumente": ["Gitarre", "Klavier", "Schlagzeug", "Flöte", "Violine", "Harfe", "Trompete", "Saxophon", "Cello", "Bass"],
      "Sport": ["Fußball", "Tennis", "Schwimmen", "Laufen", "Badminton", "Basketball", "Volleyball", "Golf", "Boxen", "Yoga"],
      "Farben": ["Rot", "Blau", "Gelb", "Weiß", "Schwarz", "Lila", "Rosa", "Orange", "Braun", "Grau"],
      "Himmlisch": ["Sonne", "Mond", "Stern", "Erde", "Mars", "Venus", "Merkur", "Jupiter", "Saturn", "Galaxie"],
      "Berufe": ["Arzt", "Lehrer", "Ingenieur", "Anwalt", "Bauer", "Bauarbeiter", "Koch", "Krankenschwester", "Pilot", "Fahrer"],
      "Fahrzeuge": ["Auto", "Flugzeug", "Schiff", "Fahrrad", "Motorrad", "Zug", "Rakete", "Hubschrauber", "Boot", "Bus"],
      "Orte": ["Haus", "Schule", "Krankenhaus", "Supermarkt", "Park", "Museum", "Kino", "Restaurant", "Hotel", "Flughafen"],
      "Objekte": ["Buch", "Stift", "Papier", "Computer", "Telefon", "Fernseher", "Radio", "Uhr", "Kamera", "Brille"],
      "Wetter": ["Regen", "Schnee", "Wind", "Nebel", "Wolke", "Sonnenschein", "Donner", "Blitz", "Überschwemmung", "Dürre"],
      "Emotionen": ["Liebe", "Hass", "Glücklich", "Traurig", "Wütend", "Ängstlich", "Überrascht", "Ruhig", "Besorgt", "Freude"]
    }
  },

  translations: {
    vi: {
      gameTitle: "CODENAMES",
      cardsFoundLabel: "Từ đã tìm",
      guessesLeft: "Lượt đoán còn lại",
      timerTotal: "Thời gian",
      aiHint: "🤖 Gợi ý từ AI Spymaster",
      btnNewHint: "Gợi ý mới",
      btnEndTurn: "Kết thúc lượt",
      btnSpymaster: "Chế độ Spymaster",
      btnNewGame: "Game mới",
      btnPlayAgain: "Chơi lại",
      youWin: "🎉 CHIẾN THẮNG!",
      youLose: "💀 THẤT BẠI!",
      timeUp: "⏰ HẾT GIỜ!",
      winMessage: "Bạn đã tìm được tất cả thẻ đỏ!",
      loseAssassin: "Bạn đã chọn thẻ Assassin!",
      loseTime: "Hết thời gian! Đội xanh thắng với",
      cardsFound: "thẻ đã tìm được.",
      hintHistory: "Lịch sử:",
      noGuessesAlert: "Hết lượt đoán! Nhấn 'Gợi ý mới' hoặc 'Kết thúc lượt'.",
      btnEndGame: "Kết thúc trò chơi",
    },
    en: {
      gameTitle: "CODENAMES",
      cardsFoundLabel: "Cards Found",
      guessesLeft: "Guesses Left",
      timerTotal: "Time",
      aiHint: "🤖 AI Spymaster Hint",
      btnNewHint: "New Hint",
      btnSpymaster: "Spymaster Mode",
      btnNewGame: "New Game",
      btnEndGame: "End Game",
      btnPlayAgain: "Play Again",
      youWin: "🎉 YOU WIN!",
      youLose: "💀 YOU LOSE!",
      timeUp: "⏰ TIME'S UP!",
      winMessage: "You found all red cards!",
      loseAssassin: "You clicked the Assassin!",
      loseTime: "Time's up! Blue team wins with",
      cardsFound: "cards found.",
      hintHistory: "History:",
      noGuessesAlert: "No guesses left! Click 'New Hint' or 'End Turn'."
    },
    fr: {
      gameTitle: "CODENAMES",
      cardsFoundLabel: "Cartes Trouvées",
      guessesLeft: "Tentatives Restantes",
      timerTotal: "Temps",
      aiHint: "🤖 Indice du Maître Espion IA",
      btnNewHint: "Nouvel Indice",
      btnSpymaster: "Mode Maître Espion",
      btnNewGame: "Nouveau Jeu",
      btnEndGame: "Terminer le Jeu",
      btnPlayAgain: "Rejouer",
      youWin: "🎉 VOUS GAGNEZ!",
      youLose: "💀 VOUS PERDEZ!",
      timeUp: "⏰ TEMPS ÉCOULÉ!",
      winMessage: "Vous avez trouvé toutes les cartes rouges!",
      loseAssassin: "Vous avez cliqué sur l'Assassin!",
      loseTime: "Temps écoulé! L'équipe bleue gagne avec",
      cardsFound: "cartes trouvées.",
      hintHistory: "Historique:",
      noGuessesAlert: "Plus de tentatives! Cliquez sur 'Nouvel Indice' ou 'Fin du Tour'."
    },
    de: {
      gameTitle: "CODENAMES",
      cardsFoundLabel: "Gefundene Karten",
      guessesLeft: "Versuche Übrig",
      timerTotal: "Zeit",
      aiHint: "🤖 KI Spymaster Hinweis",
      btnNewHint: "Neuer Hinweis",
      btnSpymaster: "Spymaster Modus",
      btnNewGame: "Neues Spiel",
      btnEndGame: "Spiel Beenden",
      btnPlayAgain: "Nochmal Spielen",
      youWin: "🎉 SIE GEWINNEN!",
      youLose: "💀 SIE VERLIEREN!",
      timeUp: "⏰ ZEIT IST UM!",
      winMessage: "Sie haben alle roten Karten gefunden!",
      loseAssassin: "Sie haben den Attentäter angeklickt!",
      loseTime: "Zeit ist um! Das blaue Team gewinnt mit",
      cardsFound: "gefundenen Karten.",
      hintHistory: "Verlauf:",
      noGuessesAlert: "Keine Versuche mehr! Klicken Sie auf 'Neuer Hinweis' oder 'Runde Beenden'."
    }
  }
};
